### ISSUE TITLE
Funcionamento no Firefox

### ISSUE THREAD

**Issue by lgrando1** [steniovm/AlgoCards#1]
Parabéns pelo projeto. Facilita muito a aplicação do Pensamento Computacional

Feedback: Não consigo arrastar as cartas do Conjunto de Instruções para o Algoritmo no Firefox.

Descrição dos passos para efetuar o erro:
1. Clonei o repositório na minha maquina
2. No terminal, fui até a pasta que contém os arquivos
3. Digitei no terminal Firefox index.html
4. Abre o arquivo no Firefox
5. Não consigo arrastar as cartas. O resto funciona normalmente.
6. Testei no Chrome sem problemas.

SO: POP_OS! 20.04
Mozila Firefox for Ubuntu - Versão 111.0.1 (64-Bits) 
Chrome - 12.0.5615.49 (Official Build) (64-bit): OK

https://user-images.githubusercontent.com/36816722/230471247-09ecbe76-abdd-49e3-bc43-4c8ed8f54d12.mp4

Caso precise de mais informações, me encontro a disposição.

**Comment by steniovm** [comment]
Obrigado pelo feedback
realmente ainda não havia testado no firefox, vou tentar resolver.

**Comment by steniovm** [comment]
Ajustado, agora funciona.
Novamente eu agradeço o aviso.

**Comment by lgrando1** [comment]
Acabei de dar o pull e funcionou perfeitamente aqui. 

Parabéns novamente pelo projeto. Acho que pode fechar a issue.
